version: "3"

services:
  market_clock_slack_messenger:
    build:
      context: .
      dockerfile: slack.dockerfile
    restart: on-failure
    volumes:
      - ./.env:/app/.env:ro

    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - MINUTES=5
    depends_on:
      - cache
    command: ["slack.py"]

  market_clock_api:
    build:
      context: .
      dockerfile: api.dockerfile
    restart: on-failure
    ports:
      - 7777:80

  cache:
    image: redis:6.0.6
    restart: on-failure
    # ports:
    # - 6379:6379
